In [1]:
import csv 
dict = {}
# opening the CSV file 
with open('../input/zoo-animal-classification/class.csv', mode ='r')as file: 
    
  # reading the CSV file 
  csvFile = csv.reader(file) 
  
  # displaying the contents of the CSV file 
  x = 0
  for lines in csvFile: 
#         print(lines)
        if x == 0:
            x = 1
        else:    
            dict[lines[0]] = lines[2]
print(dict)


{'1': 'Mammal', '2': 'Bird', '3': 'Reptile', '4': 'Fish', '5': 'Amphibian', '6': 'Bug', '7': 'Invertebrate'}


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
animals = pd.read_csv('../input/zoo-animal-classification/zoo.csv')
X = animals.iloc[:,1:-1].values
Y = animals.iloc[:, 17].values
print(X)
print("--------------------------")
print(Y)
print("----------------------------")

animals.head()

[[1 0 0 ... 0 0 1]
 [1 0 0 ... 1 0 1]
 [0 0 1 ... 1 0 0]
 ...
 [1 0 0 ... 1 0 1]
 [0 0 1 ... 0 0 0]
 [0 1 1 ... 1 0 0]]
--------------------------
[1 1 4 1 1 1 1 4 4 1 1 2 4 7 7 7 2 1 4 1 2 2 1 2 6 5 5 1 1 1 6 1 1 2 4 1 1
 2 4 6 6 2 6 2 1 1 7 1 1 1 1 6 5 7 1 1 2 2 2 2 4 4 3 1 1 1 1 1 1 1 1 2 7 4
 1 1 3 7 2 2 3 7 4 2 1 7 4 2 6 5 3 3 4 1 1 2 1 6 1 7 2]
----------------------------


animal_name  hair  feathers  eggs  milk  airborne  aquatic  predator  \
0    aardvark     1         0     0     1         0        0         1   
1    antelope     1         0     0     1         0        0         0   
2        bass     0         0     1     0         0        1         1   
3        bear     1         0     0     1         0        0         1   
4        boar     1         0     0     1         0        0         1   

   toothed  backbone  breathes  venomous  fins  legs  tail  domestic  catsize  \
0        1         1         1         0     0     4     0         0        1   
1        1         1         1         0     0     4     1         0        1   
2        1         1         0         0     1     0     1         0        0   
3        1         1         1         0     0     4     0         0        1   
4        1         1         1         0     0     4     1         0        1   

   class_type  
0           1  
1           1  
2           4  
3           1  
4           1

In [4]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size = 0.2 , random_state = 0)
print(y_train)
print("-------------------------")
print(y_test)

[3 1 2 1 1 1 2 4 3 4 3 3 1 6 1 4 2 1 1 1 4 6 2 1 7 1 6 4 1 4 2 1 4 1 1 2 1
 2 5 1 1 1 2 2 7 1 1 7 3 1 1 1 1 7 1 2 2 7 7 5 2 7 7 6 1 2 4 5 6 1 2 1 2 2
 1 6 1 1 1 1]
-------------------------
[5 4 4 1 1 1 2 4 1 1 7 1 2 7 4 6 1 6 2 4 2]


In [5]:
from sklearn.linear_model import LogisticRegression
logisticRegr = LogisticRegression()
logisticRegr.fit(x_train, y_train)

LogisticRegression()

In [6]:
predictions = logisticRegr.predict(x_test)
print(predictions)

list1 = []
for each in predictions:
    each = each.astype(str)
    list1.append(dict.get(each))
print(list1)

    

[5 4 4 1 1 1 2 4 1 1 7 1 2 7 4 6 1 6 2 4 2]
['Amphibian', 'Fish', 'Fish', 'Mammal', 'Mammal', 'Mammal', 'Bird', 'Fish', 'Mammal', 'Mammal', 'Invertebrate', 'Mammal', 'Bird', 'Invertebrate', 'Fish', 'Bug', 'Mammal', 'Bug', 'Bird', 'Fish', 'Bird']


In [7]:
score = logisticRegr.score(x_test, y_test)
print(score)

1.0


In [8]:
from sklearn import metrics
cm = metrics.confusion_matrix(y_test, predictions)
print(cm)

[[7 0 0 0 0 0]
 [0 4 0 0 0 0]
 [0 0 5 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 2 0]
 [0 0 0 0 0 2]]
